language: csharp
sudo: required
mono: none
services:
  - docker
before_install: 
  - docker build -t bieszczyk/webapplication -f ./WebApplications/Dockerfile.build .

script: 
  - docker run bieszczyk/webapplication
